# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a60deb76d2107548c372c1546a08d71baac02364883d7b9a4e5b2543a718c9e702749714da21748e894fa6506f54afcad2f65d537dd0212396d1d18bca343455

test:
  secret_key_base: d8b0e02a77222bce9e4ae343c4c9f5ce91d8a413d16308d937cfb4a6a984a2acf97816b2e66fd98486f57abd8b6f415f60a0637c3e1899846dea0b4a8add4c43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
